const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/collections' : 'Collections',
  '/connection': 'Connection',
  '/gps': 'GPS',
  '/cloud': 'Cloud',
  '/survey': 'Survey',
  '/licenses':'Licenses',
  './about':'About',

  '/logging': 'Logging',
  '/firmware': 'Firmware',

  '/components': 'Components',
  '/charts': 'Charts',
  '/connection/wifi': 'WiFi',
  '/connection/bluetooth': 'BlueTooth',
  '/connection/cable': 'Cable',
  '/gps/main': 'Main',
  '/gps/device': 'Device',
  '/gps/calibration': 'Calibration',
  '/gps/radios':'Radios',
  '/gps/ntrip':'NTRIP',
  '/gps/senzors':'Senzors',
  '/gps/firmware':'Firmware',
  '/gps/starfire':'StarFire',
  '/gps/basecord':'BaseCord',
  '/gps/logdata':'LogData',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Buttons',
  '/components/cards': 'CableView',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/widgets': 'Widgets'
};
export default routes;
